apiVersion: apps/v1
kind: Deployment
metadata:
  name: newsugar-frontend-prod
  namespace: default
  labels:
    app: newsugar-frontend
    env: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: newsugar-frontend
      env: prod
  template:
    metadata:
      labels:
        app: newsugar-frontend
        env: prod
    spec:
      containers:
        - name: newsugar-frontend
          # ECR 이미지 경로 (프론트엔드용 ECR 레포)
          # AWS Account ID: 061039804626
          image: 061039804626.dkr.ecr.ap-northeast-2.amazonaws.com/newsugar-frontend:prod
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
